springdata:
  image: goodraincloudframeworks/springdata
  ports:
    - 8080:8080
  container_name: springdata

kong-database:
  image: postgres
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong
  container_name: kong-database

kong:
  image: kong
  links:
    - kong-database:kong-database
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
  expose:
    - 7946
    - 7946/udp
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
  container_name: kong

kong-dashboard:
  image: goodraincloudframeworks/docker-kong-dashboard
  ports:
    - 5000:5000
  container_name: kong-dashboard


