springdata:
  image: goodraincloudframeworks/springdata
  ports:
    - 8080:8080
  container_name: springdata

kong-database:
  image: postgres:9.5
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong
    - POSTGRES_PASSWORD=kong
  volumes:
    - /kongdata:/var/lib/postgresql/data
  container_name: kong-database

kong:
  image: goodraincloudframeworks/kong
  restart: always
  links:
    - kong-database:kong-database
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database
    - KONG_PG_USER=kong
    - KONG_PG_DATABASE=kong
    - KONG_PG_PAASWORD=kong
  container_name: kong

kong-dashboard:
  image: goodraincloudframeworks/kong-dashboard
  links:
    - kong:kongadmin
  environment:
    - KONGADMIN_HOST=kongadmin
    - KONGADMIN_PORT=8001
  ports:
    - 5000:5000
  container_name: kong-dashboard


